//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef THERMALVIEW_THERMALVIEW_WXCRAFTER_BASE_CLASSES_H
#define THERMALVIEW_THERMALVIEW_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include "wximageview.h"
#include <wx/slider.h>
#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/listbox.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/clrpicker.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MainDialogBaseClass : public wxDialog
{
protected:
    wxImageView* m_picture;
    wxImageView* m_gradient;
    wxSlider* m_slider_low;
    wxSlider* m_slider_high;
    wxButton* m_button_connect;
    wxButton* m_button_stop;
    wxButton* m_button_take_one;
    wxButton* m_button_get_cal;
    wxCheckBox* m_check_use_extra_cal;
    wxChoice* m_lb_interpolation;
    wxChoice* m_lb_profile;
    wxButton* m_button_edit_profile;
    wxCheckBox* m_check_auto_range;
    wxImageView* m_histogram;
    wxButton* m_button_save;
    wxChoice* m_lb_sizes;

protected:
    virtual void OnSlider_lowScrollChanged(wxScrollEvent& event) { event.Skip(); }
    virtual void OnSlider_highScrollChanged(wxScrollEvent& event) { event.Skip(); }
    virtual void OnButton_connectButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_stopButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_take_oneButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_get_calButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCheck_use_extra_calCheckboxClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnLb_interpolationChoiceSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnLb_profileChoiceSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_edit_profileButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCheck_auto_rangeCheckboxClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_saveButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxImageView* GetPicture() { return m_picture; }
    wxImageView* GetGradient() { return m_gradient; }
    wxSlider* GetSlider_low() { return m_slider_low; }
    wxSlider* GetSlider_high() { return m_slider_high; }
    wxButton* GetButton_connect() { return m_button_connect; }
    wxButton* GetButton_stop() { return m_button_stop; }
    wxButton* GetButton_take_one() { return m_button_take_one; }
    wxButton* GetButton_get_cal() { return m_button_get_cal; }
    wxCheckBox* GetCheck_use_extra_cal() { return m_check_use_extra_cal; }
    wxChoice* GetLb_interpolation() { return m_lb_interpolation; }
    wxChoice* GetLb_profile() { return m_lb_profile; }
    wxButton* GetButton_edit_profile() { return m_button_edit_profile; }
    wxCheckBox* GetCheck_auto_range() { return m_check_auto_range; }
    wxImageView* GetHistogram() { return m_histogram; }
    wxButton* GetButton_save() { return m_button_save; }
    wxChoice* GetLb_sizes() { return m_lb_sizes; }
    MainDialogBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Thermal View"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(615,467), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX);
    virtual ~MainDialogBaseClass();
};


class ProfileEditorDialogBase : public wxDialog
{
protected:
    wxListBox* m_lb_pattern;
    wxStaticText* m_staticText103;
    wxTextCtrl* m_text_granularity;
    wxTextCtrl* m_text_rank;
    wxTextCtrl* m_text_color;
    wxColourPickerCtrl* m_colour_picker;
    wxButton* m_button_add;
    wxButton* m_button_rem;
    wxCheckBox* m_check_preview;
    wxButton* m_button_apply;
    wxButton* m_button_save;
    wxButton* m_button_save_as;

protected:
    virtual void OnLb_patternListboxSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void OnText_granularityTextUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void OnText_rankTextUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void OnText_colorTextUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void OnColour_pickerColourpickerChanged(wxColourPickerEvent& event) { event.Skip(); }
    virtual void OnButton_addButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_remButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCheck_previewCheckboxClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_applyButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_saveButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_save_asButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxListBox* GetLb_pattern() { return m_lb_pattern; }
    wxStaticText* GetStaticText103() { return m_staticText103; }
    wxTextCtrl* GetText_granularity() { return m_text_granularity; }
    wxTextCtrl* GetText_rank() { return m_text_rank; }
    wxTextCtrl* GetText_color() { return m_text_color; }
    wxColourPickerCtrl* GetColour_picker() { return m_colour_picker; }
    wxButton* GetButton_add() { return m_button_add; }
    wxButton* GetButton_rem() { return m_button_rem; }
    wxCheckBox* GetCheck_preview() { return m_check_preview; }
    wxButton* GetButton_apply() { return m_button_apply; }
    wxButton* GetButton_save() { return m_button_save; }
    wxButton* GetButton_save_as() { return m_button_save_as; }
    ProfileEditorDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Edit Profile"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(235,300), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~ProfileEditorDialogBase();
};

#endif
