//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainDialogBaseClass::MainDialogBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(mainSizer);
    
    wxBoxSizer* boxSizer17 = new wxBoxSizer(wxHORIZONTAL);
    
    mainSizer->Add(boxSizer17, 1, wxALL|wxEXPAND, 5);
    
    m_picture = new wxImageView(this, wxID_ANY);
    boxSizer17->Add(m_picture, 1, wxALL|wxEXPAND, 5);
    
    m_gradient = new wxImageView(this, wxID_ANY);
    boxSizer17->Add(m_gradient, 0, wxRIGHT|wxTOP|wxBOTTOM|wxEXPAND, 5);
    m_gradient->SetMinSize(wxSize(15,-1));
    
    wxBoxSizer* boxSizer19 = new wxBoxSizer(wxVERTICAL);
    
    boxSizer17->Add(boxSizer19, 0, wxALL|wxEXPAND, 5);
    
    m_button_connect = new wxButton(this, wxID_ANY, _("Connect"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer19->Add(m_button_connect, 0, wxALL|wxEXPAND, 5);
    
    m_button_stop = new wxButton(this, wxID_ANY, _("Stop"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_button_stop->Enable(false);
    
    boxSizer19->Add(m_button_stop, 0, wxALL|wxEXPAND, 5);
    
    m_button_take_one = new wxButton(this, wxID_ANY, _("Take One"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_button_take_one->Enable(false);
    
    boxSizer19->Add(m_button_take_one, 0, wxALL|wxEXPAND, 5);
    
    m_button_get_cal = new wxButton(this, wxID_ANY, _("Do Extra Cal"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_button_get_cal->SetToolTip(_("Point your camera down and wait for the calibration frame."));
    m_button_get_cal->Enable(false);
    
    boxSizer19->Add(m_button_get_cal, 0, wxALL|wxEXPAND, 5);
    
    m_check_use_extra_cal = new wxCheckBox(this, wxID_ANY, _("Use Extra Cal"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_check_use_extra_cal->SetValue(false);
    
    boxSizer19->Add(m_check_use_extra_cal, 0, wxALL, 5);
    
    wxArrayString m_lb_profileArr;
    m_lb_profile = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), m_lb_profileArr, 0);
    
    boxSizer19->Add(m_lb_profile, 0, wxALL|wxEXPAND, 5);
    m_lb_profile->SetMinSize(wxSize(87,-1));
    
    boxSizer19->Add(0, 0, 1, wxALL, 5);
    
    m_button_save = new wxButton(this, wxID_ANY, _("Save"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_button_save->Enable(false);
    
    boxSizer19->Add(m_button_save, 0, wxALL|wxEXPAND, 5);
    
    wxArrayString m_lb_sizesArr;
    m_lb_sizes = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), m_lb_sizesArr, 0);
    
    boxSizer19->Add(m_lb_sizes, 0, wxALL|wxEXPAND, 5);
    m_lb_sizes->SetMinSize(wxSize(87,-1));
    
    SetName(wxT("MainDialogBaseClass"));
    SetSizeHints(615,400);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    CentreOnParent(wxBOTH);
    // Connect events
    m_button_connect->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_connectButtonClicked), NULL, this);
    m_button_stop->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_stopButtonClicked), NULL, this);
    m_button_take_one->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_take_oneButtonClicked), NULL, this);
    m_button_get_cal->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_get_calButtonClicked), NULL, this);
    m_check_use_extra_cal->Connect(wxEVT_COMMAND_CHECKBOX_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnCheck_use_extra_calCheckboxClicked), NULL, this);
    m_lb_profile->Connect(wxEVT_COMMAND_CHOICE_SELECTED, wxCommandEventHandler(MainDialogBaseClass::OnLb_profileChoiceSelected), NULL, this);
    m_button_save->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_saveButtonClicked), NULL, this);
    
}

MainDialogBaseClass::~MainDialogBaseClass()
{
    m_button_connect->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_connectButtonClicked), NULL, this);
    m_button_stop->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_stopButtonClicked), NULL, this);
    m_button_take_one->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_take_oneButtonClicked), NULL, this);
    m_button_get_cal->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_get_calButtonClicked), NULL, this);
    m_check_use_extra_cal->Disconnect(wxEVT_COMMAND_CHECKBOX_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnCheck_use_extra_calCheckboxClicked), NULL, this);
    m_lb_profile->Disconnect(wxEVT_COMMAND_CHOICE_SELECTED, wxCommandEventHandler(MainDialogBaseClass::OnLb_profileChoiceSelected), NULL, this);
    m_button_save->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnButton_saveButtonClicked), NULL, this);
    
}
